#!/bin/bash -x
set -e

mydir="$(dirname "$0")"
BUILD_ARGS=("$@")

B() {
	local name="$1"
	shift
	(cd "$name" && make "${BUILD_AGS[@]}" || echo "Build of ${name} failed" >&2 ; )
}

source "$mydir/build-names"
