#!/bin/bash
set -e

mydir="$(dirname "$0")"
mydir="$(readlink -f "$mydir")"
export BUILD_ARGS=("$@")

export ERRORS=

for d in "$mydir/build-configs"/*;do
	name="$(basename "$d")"
	if ! ( cd "$name" && make "${BUILD_ARGS[@]}"; );then
		echo "ERROR: Build of ${name} failed" >&2
		ERRORS="$ERRORS ${name}"
	fi
done

source "$mydir/build-names"

if [ -n "$ERRORS" ];then
	echo ERRORS ABOVE: $ERRORS >&2
	exit 1
fi
