#!/bin/bash -x
set -e

mydir="$(dirname "$0")"
export BUILD_ARGS=("$@")

B() {
	local name="$1"
	shift
	(cd "$name" && make "${BUILD_ARGS[@]}" || echo "Build of ${name} failed" >&2 ; )
}

source "$mydir/build-names"
