#!/bin/bash -x
set -e

mydir="$(dirname "$0")"

B() {
	local name="$1"
	shift
	mkdir -p "$name"
	if ! ( cd "$name" && ../configure "$@"; );then
		echo "ERROR: Configure of ${name} failed" >&2
		ERRORS="$ERRORS ${name}"
	fi
}

source "$mydir/build-names"

if [ -n "$ERRORS" ];then
	echo ERRORS ABOVE: $ERRORS >&2
	exit 1
fi
