#!/bin/bash -x
set -e

mydir="$(dirname "$0")"
ARGS=("$@")

if [ -f vl.c ];then
	QEMU_DIR=".."
else
	QEMU_DIR="$(readlink -f "$mydir")/../qemu"
fi

B() {
	local name="$1"
	shift
	mkdir -p "$name"
	if ! ( cd "$name" && "$QEMU_DIR"/configure "$@" "${ARGS[@]}"; );then
		echo "ERROR: Configure of ${name} failed" >&2
		ERRORS="$ERRORS ${name}"
	fi
}

source "$mydir/build-names"

if [ -n "$ERRORS" ];then
	echo ERRORS ABOVE: $ERRORS >&2
	exit 1
fi
