#!/bin/bash

MYDIR="$(dirname "$0")"

QEMUS=()
while [ $# -gt 0 ];do
	case "$1" in
		-*)
		break
		;;
		*)
		# let's hope every single QEMU argument starts with "-"
		QEMUS+=("$1")
		shift
	esac
done

QEMUARGS=()
while [ $# -gt 0 ];do
	arg="$1"
	shift
	if [ "$arg" = "--" ];then
		break
	fi
	QEMUARGS+=("$arg")
done

QMP=()
while [ $# -gt 0 ];do
	arg="$1"
	shift
	QMP+=("$arg")
done

SOCK="$(mktemp /tmp/qmp.XXXXXX)"

for QEMU in "${QEMUS[@]}";do
	"$QEMU" "${QEMUARGS[@]}" -qmp "unix:$SOCK,server,nowait" -daemonize
	"$MYDIR"/qmp/qmp-shell "$SOCK" "${QMP[@]}"
	"$MYDIR"/qmp/qmp-shell "$SOCK" "quit" > /dev/null
	wait
done