#!/bin/bash

MYDIR="$(dirname "$0")"

QEMU=()
while [ $# -gt 0 ];do
	arg="$1"
	shift
	if [ "$arg" = "--" ];then
		break
	fi
	QEMU+=("$arg")
done

QMP=()
while [ $# -gt 0 ];do
	arg="$1"
	shift
	QMP+=("$arg")
done

SOCK="$(mktemp /tmp/qmp.XXXXXX)"

"${QEMU[@]}" -qmp "unix:$SOCK,server,nowait" -daemonize
"$MYDIR"/qmp/qmp-shell "$SOCK" "${QMP[@]}"
"$MYDIR"/qmp/qmp-shell "$SOCK" "quit" > /dev/null
wait

