FROM ubuntu:precise
MAINTAINER Eduardo Habkost <ehabkost@redhat.com>
RUN apt-get update && apt-get install -y \
	python gcc pkg-config zlib1g-dev \
	libglib2.0 libpixman-1-dev libpixman-1-dev \
	libpixman-1-dev libfdt-dev make
